add healthcheck cmd to probe live and ready
kubeovn/kube-ovn pull request #1196
Opened 2021-12-23 09:06 UTC by A-Zee029

#### What type of this PR
- Performance

#### Which issue(s) this PR fixes:
#1153

2021-12-24 02:09 UTC, zhangzujian commented on dist/images/install.sh
> +                - ./kube-ovn-controller-healthcheck
We should use the absolute path `/kube-ovn/kube-ovn-controller-healthcheck` instead.

2021-12-24 02:13 UTC, zhangzujian commented on cmd/controller_health_check/controller_health_check.go
> +	}
Read the file content using `os.ReadFile`.

2021-12-27 02:10 UTC, oilbeater commented on cmd/controller_health_check/controller_health_check.go
> +		klog.Errorf("failed to get ovn-nbctl daemon pid, %s", err)
it's better to use `klog.Fatalf` to mereg the errorf and exit

2021-12-27 02:11 UTC, oilbeater requested changes

2021-12-27 02:11 UTC, oilbeater commented on cmd/controller_health_check/controller_health_check.go
> +		klog.Errorf("failed to get ovn-nbctl daemon pid, %s", err)
it's better to use `klog.Fatalf` to mereg the errorf and exit

2021-12-27 02:12 UTC, oilbeater commented
Please squash the commits into one commit

2021-12-27 02:16 UTC, zhangzujian commented
`kube-ovn-controller-healthcheck.sh` should be removed.

2021-12-28 01:41 UTC, oilbeater approved these changes

2021-12-28 01:41 UTC, merged

2021-12-28 01:41 UTC, oilbeater commented
Thanks! @A-Zee029