feat: Replace command health check with k8s tcpSocket check
kubeovn/kube-ovn pull request #1251
Opened 2022-01-11 09:41 UTC by sober-wang

I want try to contributor the project. so find the #1150 is a good first issue.

2022-01-12 02:09 UTC, oilbeater commented
@sober-wang you should also update the `install.sh` script

2022-01-12 02:09 UTC, oilbeater requested changes

2022-01-12 02:09 UTC, oilbeater commented on yamls/kube-ovn.yaml
> +            timeoutSeconds: 1
`timeoutSeconds` should be long enough, when the system load is high it may not response in 1 second

2022-01-12 02:09 UTC, oilbeater commented on yamls/kube-ovn.yaml
> +            timeoutSeconds: 1
same as above

2022-01-12 09:50 UTC, oilbeater commented
`timeoutSeconds` should be increased to 10,  and please squash the commits into one

2022-01-13 05:36 UTC, sober-wang commented
> `yamls/kube-ovn-ipv6.yaml` and `yamls/kube-ovn-dual-stack.yaml` should be updated too.

Thanks for your point out.

2022-01-13 06:47 UTC, oilbeater commented
please check https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch to squash commits

2022-01-15 01:54 UTC, sober-wang commented
> please check https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch to squash commits

Your mean's Should  I created a branch, next the pull request from the new branch?

2022-01-19 04:30 UTC, zhangzujian commented
@sober-wang  Merge the changes into one commit, and then force push to the PR's source branch *sober-wang:master*.

[Squash my last X commits together using Git](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)

2022-02-08 09:47 UTC, merged

2022-02-08 09:47 UTC, oilbeater commented
Squashed the commit by github squash merge. Thanks! @sober-wang