Support only static mac_address
kubeovn/kube-ovn pull request #1253
Opened 2022-01-11 15:40 UTC by chestack

#### Which issue(s) this PR fixes:
Fixes #1252

2022-01-12 01:43 UTC, hongzhen-ma requested changes

2022-01-12 01:43 UTC, hongzhen-ma commented on pkg/controller/pod.go
> +					klog.Infof("Use the configured static mac address %s mac for pod %s.", pod.Name, mac)
parameter order is wrong

2022-01-12 02:09 UTC, chestack commented on pkg/controller/pod.go
> +					klog.Infof("Use the configured static mac address %s mac for pod %s.", pod.Name, mac)
done in new commit

2022-01-12 03:02 UTC, chestack commented on pkg/controller/pod.go
> +					klog.Infof("Use the configured static mac address %s mac for pod %s.", pod.Name, mac)
> 直接修改返回的mac地址，这样不合适 在ipam中分配mac地址的时候，有记录pod与mac映射关系，可以看下subnet.GetRandomMac

en, 修改的时候 注意到了这个问题，subnet.GetRandomMac() 会产生一个random mac，输出一条日志，但实际 数据库里(kubectl get ips  和  ovn-nbcl show <subnet>)里记录的是macStr，所以没 改成用  subnet.GetStaticMac()


> 静态分配地址的情况下，mac地址都是可以使用指定的mac，如果没有指定，就会动态分配mac。 这里是动态分配地址的处理，什么情况下，ip可以动态分配，但是又需要单独指定mac地址？

场景是 kubevirt+kube-ovn，只mac固定是基于以下两个原因:
1. kubevirt VM restart 依赖 mac固定 [kubevirt/kubevirt#1251](https://github.com/kubevirt/kubevirt/issues/1251)，每个vm都依赖mac 固定，但不是每个vm要ip 固定
2. ip固定 live migration 目前有限制： https://github.com/kubeovn/kube-ovn/issues/663


综上，ip动态分配 单独指定mac这个场景 建议可以考虑支持， 代码逻辑上我再改下

2022-01-12 07:09 UTC, chestack commented on pkg/controller/pod.go
>  	macStr := pod.Annotations[fmt.Sprintf(util.MacAddressAnnotationTemplate, podNet.ProviderName)]
add validation in new commit

2022-01-12 10:25 UTC, hongzhen-ma requested changes

2022-01-12 10:25 UTC, hongzhen-ma commented on pkg/controller/pod.go
> +				ipv4, ipv6, mac, err = c.ipam.GetRandomIPAddressWithStaticMac(key, nicName, macStr, podNet.Subnet.Name, skippedAddrs)
感觉可以不用新加这个函数，在原来的函数里边加个macStr参数就可以了吧？
处理上看着没啥区别，到最后ipam中申请ip地址的时候，macStr也做了检查，有没有值都是支持的

2022-01-12 11:56 UTC, chestack commented on pkg/controller/pod.go
> +				ipv4, ipv6, mac, err = c.ipam.GetRandomIPAddressWithStaticMac(key, nicName, macStr, podNet.Subnet.Name, skippedAddrs)
GetRandomIPAddress() UT里用的比较多... 所以加了新方法

一个函数更好维护的话，参数加到GetRandomIPAddress()里吧

2022-01-13 02:09 UTC, hongzhen-ma approved these changes

2022-01-13 03:12 UTC, merged