feat: vpc peering connection
kubeovn/kube-ovn pull request #1292
Opened 2022-02-13 10:00 UTC by fanriming

#### What type of this PR
Examples of user facing changes:
- API changes

Bring VPC Peering feature to kube-ovn
https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html

#### OVN command example
```
ovn-nbctl lr-add lr0
ovn-nbctl lr-add lr1
ovn-nbctl lrp-add lr0 lr0-p0 00:11:22:33:44:55 192.168.10.10/24 peer=lr1-p0
ovn-nbctl lrp-add lr1 lr1-p0 00:11:22:33:44:66 192.168.20.10/24 peer=lr0-p0
ovn-nbctl lrp-del lr1-p0
```
#### USAGE
Create two VPCs with static route and peering connection
```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec: 
  staticRoutes:
  - cidr: 10.0.2.0/24
    nextHopIP: 169.254.0.2
    policy: policyDst
  vpcPeerings:
  - localConnectIP: 169.254.0.1/30
    remoteVpc: test-vpc-2
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  default: true
  natOutgoing: false
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-2
spec: 
  staticRoutes:
  - cidr: 10.0.1.0/24
    nextHopIP: 169.254.0.1
    policy: policyDst
  vpcPeerings:
  - localConnectIP: 169.254.0.2/30
    remoteVpc: test-vpc-1
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net2
spec:
  vpc: test-vpc-2
  cidrBlock: 10.0.2.0/24
  natOutgoing: false
```
Traceroute result 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/16485892/153748004-12f7029c-0aa4-44b7-89f5-6bc95fac25d4.png">

2022-02-14 05:50 UTC, oilbeater requested changes

2022-02-14 05:50 UTC, oilbeater commented on pkg/controller/gc.go
> +		klog.Errorf("failed to list logical switch port, %v", err)
`logical switch port` -> `logical router port`

2022-02-14 05:50 UTC, oilbeater commented on pkg/controller/gc.go
> +			exceptPeerPorts = append(exceptPeerPorts, fmt.Sprintf(vpc.Name, peer))
`fmt.Sprintf("%s-%s")`

2022-02-14 05:50 UTC, oilbeater commented on pkg/ovs/ovn-nbctl.go
> +func (c Client) GetLogicalRouterPortNetworks(port string) ([]string, error) {
This function is not used

2022-02-14 05:50 UTC, oilbeater commented
@fanriming can you  add the docs?

2022-02-14 08:05 UTC, fanriming commented
@oilbeater

2022-02-14 08:05 UTC, fanriming commented on pkg/controller/gc.go
> +		klog.Errorf("failed to list logical switch port, %v", err)
fixed

2022-02-14 08:05 UTC, fanriming commented on pkg/controller/gc.go
> +			exceptPeerPorts = append(exceptPeerPorts, fmt.Sprintf(vpc.Name, peer))
fixed

2022-02-14 08:05 UTC, fanriming commented on pkg/ovs/ovn-nbctl.go
> +func (c Client) GetLogicalRouterPortNetworks(port string) ([]string, error) {
fixed

2022-02-14 08:07 UTC, fanriming commented
> @fanriming can you add the docs?
Docs has been added to commit now.

2022-02-14 09:48 UTC, oilbeater approved these changes

2022-02-14 09:48 UTC, merged

2022-03-01 09:01 UTC, xujunjie-cover commented
Can it support visit peer vpc service ?