support dpdk
kubeovn/kube-ovn pull request #1317
Opened 2022-02-23 01:59 UTC by luoyunhe

#### What type of this PR
Examples of user facing changes:
- API changes
- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #(issue-number)

2022-03-02 06:44 UTC, oilbeater commented
@luoyunhe the  `tmp/Dockerfile` should be removed

2022-03-02 06:51 UTC, luoyunhe commented
> @luoyunhe the `tmp/Dockerfile` should be removed

ok, Could you give me some suggestions for this PR, thanks.

2022-03-02 10:30 UTC, oilbeater commented
@luoyunhe it looks good to me now. I will test the pr in my cluster later and will let you know if something need to change

2022-03-11 07:06 UTC, oilbeater requested changes

2022-03-11 07:06 UTC, oilbeater commented on pkg/daemon/handler.go
> +		err = os.MkdirAll(newSharedDir, 0750)
error handle format

2022-03-11 07:06 UTC, oilbeater commented on pkg/daemon/handler.go
> +	_, err = os.Stat(sharedDir)
error handle format

2022-03-11 07:06 UTC, oilbeater commented on pkg/daemon/handler.go
> +			err = removeShortSharedDir(pod, podRequest.VhostUserSocketVolumeName)
error handle format

2022-03-11 07:06 UTC, oilbeater commented on pkg/daemon/handler.go
> +	if os.IsNotExist(err) {
other error should also be reported

2022-03-11 07:23 UTC, luoyunhe commented on pkg/daemon/config.go
> +		config.Iface = "br-phy"
这里获取的IP会作为隧道封包IP，使用这个IP可以使用户态的DPDK直接收到封包数据，关于用户态的隧道配置可以参照这个OvS的文档：https://github.com/openvswitch/ovs/blob/master/Documentation/howto/userspace-tunneling.rst

2022-03-11 07:53 UTC, luoyunhe commented on pkg/daemon/handler.go
> +		return fmt.Errorf("can not fount volume %s in pod %s", volumeName, pod.Name)
fix

2022-03-11 07:53 UTC, luoyunhe commented on docs/dpdk-hybrid.md
> +Just run install.sh --with-hybrid-dpdk
ok

2022-03-11 08:26 UTC, oilbeater requested changes

2022-03-11 08:26 UTC, oilbeater commented on pkg/daemon/config.go
> +		config.Iface = "br-phy"
这个名字应该是可配的，不应该写死在这里

2022-03-11 08:50 UTC, luoyunhe commented on pkg/daemon/config.go
> +		config.Iface = "br-phy"
已经完成修改

2022-03-11 09:16 UTC, oilbeater approved these changes

2022-03-11 09:24 UTC, merged

2022-03-11 09:24 UTC, oilbeater commented
Great work! Thanks @luoyunhe