release update 1.8.3 changelog
kubeovn/kube-ovn pull request #1360
Opened 2022-03-07 09:10 UTC by lut777

2022-03-08 05:49 UTC, hongzhen-ma requested changes

2022-03-08 05:49 UTC, hongzhen-ma commented on CHANGELOG.md
> +- add metric for ovn nb/sb db status
这两个不能算到性能里边，可以算优化

2022-03-08 05:49 UTC, hongzhen-ma commented on CHANGELOG.md
> +- feat update provider network via node annotation
这个算feature吧

2022-03-08 05:49 UTC, hongzhen-ma commented on CHANGELOG.md
> +- keep ip for kubevirt pod
这个也算feature

2022-03-09 02:11 UTC, lut777 commented on CHANGELOG.md
> +- keep ip for kubevirt pod
moved.

2022-03-09 02:11 UTC, lut777 commented on CHANGELOG.md
> +- feat update provider network via node annotation
moved.

2022-03-09 02:11 UTC, lut777 commented on CHANGELOG.md
> +- add metric for ovn nb/sb db status
moved

2022-03-09 02:44 UTC, hongzhen-ma approved these changes

2022-03-09 09:53 UTC, merged