release update 1.9.1 changelog
kubeovn/kube-ovn pull request #1361
Opened 2022-03-07 13:56 UTC by lut777

2022-03-08 06:02 UTC, hongzhen-ma requested changes

2022-03-08 06:02 UTC, hongzhen-ma commented on docs/cluster-interconnection.md
> +docker run --name=ovn-ic-db -d --network=host -v /etc/ovn/:/etc/ovn -v /var/run/ovn:/var/run/ovn -v /var/log/ovn:/var/log/ovn -e LOCAL_IP="LOCALIP"  -e NODE_IPS="IP1,IP2,IP3" -e LEADER_IP="LEADERIP"
确定是要分行执行吗

2022-03-09 02:05 UTC, lut777 commented on CHANGELOG.md
> +- update networkpolicy port process
moved

2022-03-09 02:06 UTC, lut777 commented on CHANGELOG.md
> +- append htbqos para in crd yaml
moved.

2022-03-09 02:06 UTC, lut777 commented on CHANGELOG.md
> +- update flag parse in webhook
moved.

2022-03-09 02:41 UTC, hongzhen-ma approved these changes

2022-03-09 09:53 UTC, merged