Support kubevirt vm live migrate for pod static ip
kubeovn/kube-ovn pull request #1468
Opened 2022-04-22 02:25 UTC by hwjiangkai

#### What type of this PR
- Bug fixes
kube-ovn-webhook need to support for kubevirt VM live migration scenario

#### Which issue(s) this PR fixes:
Fixes #1462

2022-04-22 07:53 UTC, hongzhen-ma commented on pkg/webhook/static_ip.go
> +			providerName = util.OvnProvider
1、可以看下pod.go 文件 getPodAttachmentNet 的实现，如果不是由kube-ovn来提供附加网卡的功能，需不需要单独处理

2、multus作为默认网卡提供IP功能，现在已经支持了，在这种情况下，provider的名称，不是ovn，所以这里应该不需要单独处理 isDefault 的情况了

2022-04-22 08:08 UTC, hongzhen-ma commented on pkg/webhook/static_ip.go
> +			providerName = util.OvnProvider
问题2 使用multus提供默认网卡的时候，annotation类似这样
<img width="910" alt="image" src="https://user-images.githubusercontent.com/67130442/164645910-7ae8304c-d4e2-4456-83d2-0204ca3601e9.png">

2022-04-22 08:19 UTC, hongzhen-ma requested changes

2022-04-22 08:19 UTC, hongzhen-ma commented on pkg/webhook/static_ip.go
> +			providerName = util.OvnProvider
问题1 不用单独处理

2022-04-22 08:29 UTC, hongzhen-ma commented on pkg/webhook/static_ip.go
> +			providerName = util.OvnProvider
问题1 不用单独处理

2022-04-23 03:09 UTC, hwjiangkai commented on pkg/webhook/static_ip.go
> +			providerName = util.OvnProvider
问题1考虑过，可以不用单独处理，否则需要再引入networkClient，增加复杂度
问题2我修改下，thanks

2022-04-23 03:21 UTC, hwjiangkai commented on pkg/webhook/static_ip.go
> +			providerName = util.OvnProvider
done

2022-04-24 01:29 UTC, hongzhen-ma approved these changes

2022-04-24 02:03 UTC, merged