add delete ovs pods after restore nb db
kubeovn/kube-ovn pull request #1474
Opened 2022-04-24 07:14 UTC by hongzhen-ma

#### What type of this PR
- Bug fixes
####
add delete ovs pods after restore nb db

#### Which issue(s) this PR fixes:
Fixes #(issue-number)

2022-04-24 07:52 UTC, oilbeater requested changes

2022-04-24 07:52 UTC, oilbeater commented on dist/images/install.sh
> +          podNames=`kubectl get pod -n $KUBE_OVN_NS | grep ovs-ovn | awk '{print $1}'`
kubectl delete pod -n $KUBE_OVN_NS -lapp=ovs

2022-04-24 08:27 UTC, hongzhen-ma commented on dist/images/restore-ovn-nb-db.sh
> +kubectl delete pod -n $KUBE_OVN_NS -l app=ovs
镜像中应该删掉了kubectl的文件，脚本执行还要依赖这个

2022-04-24 08:27 UTC, hongzhen-ma commented on dist/images/install.sh
> +          podNames=`kubectl get pod -n $KUBE_OVN_NS | grep ovs-ovn | awk '{print $1}'`
modified

2022-04-25 02:17 UTC, oilbeater commented on dist/images/restore-ovn-nb-db.sh
> +kubectl delete pod -n $KUBE_OVN_NS -l app=ovs
镜像我修改一下

2022-04-25 02:17 UTC, oilbeater approved these changes

2022-04-25 02:29 UTC, merged

2022-04-25 02:38 UTC, hongzhen-ma commented
修改已回合release-1.8 和 release-1.9 分支