Develop switch lb rule
kubeovn/kube-ovn pull request #1656
Opened 2022-06-28 10:00 UTC by ShaPoHun

# 自定义switch lb rule使用方式
```yaml
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name:  cjh-slr-nginx
spec:
  vip: 1.1.1.1
  sessionAffinity: ClientIP
  namespace: default
  selector:
    - app:nginx
  ports:
  - name: dns
    port: 8888
    targetPort: 80
    protocol: TCP
```
* 与k8s service类型的参数：

  * selector
  * sessionAffinity
  * ports
* `vip`：指定 lb的vip
* `namespace`：`selector`后端的部署位置

部署后信息显示：
```
[root@hci-dev-mst-1 ~]# kubectl get slr
NAME                VIP         PORT(S)                  SERVICE                             AGE
vpc-dns-test-cjh2   10.96.0.3   53/UDP,53/TCP,9153/TCP   kube-system/slr-vpc-dns-test-cjh2   88m
```

2022-07-06 03:52 UTC, oilbeater requested changes

2022-07-06 03:52 UTC, oilbeater commented on pkg/controller/endpoint.go
> +	var settingIPs []string
settingIPs -> LbIPs

2022-07-06 03:52 UTC, oilbeater commented on pkg/controller/switch_lb_rule.go
> +	if err != nil {
should check not found error and just return

2022-07-11 09:49 UTC, oilbeater approved these changes

2022-07-11 09:50 UTC, oilbeater commented
Great work! Thanks @ShaPoHun

2022-07-11 09:50 UTC, merged

2022-08-16 06:45 UTC, ShaPoHun commented
[自定义switch lb rule使用方式.md](https://github.com/kubeovn/kube-ovn/files/9348448/switch.lb.rule.md)