Develop custom vpc-dns
kubeovn/kube-ovn pull request #1662
Opened 2022-07-01 06:57 UTC by ShaPoHun

[自定义vpc-dns使用方式.md](https://github.com/kubeovn/kube-ovn/files/9026744/vpc-dns.md)

2022-07-06 05:37 UTC, oilbeater commented
需要等 https://github.com/kubeovn/kube-ovn/pull/1656 合并后再看，一些代码需要对应调整

2022-07-11 09:51 UTC, oilbeater commented
should rebase master to resolve the conflict

2022-07-13 15:09 UTC, oilbeater commented
需要在 gc 里考虑新资源不一致情况下的回收

2022-07-19 06:11 UTC, oilbeater approved these changes

2022-07-19 06:13 UTC, oilbeater requested changes

2022-07-19 06:13 UTC, oilbeater commented on pkg/controller/vpc_dns.go
> +
should check error here

2022-07-19 06:26 UTC, ShaPoHun commented
[自定义vpc-dns使用方式.md](https://github.com/kubeovn/kube-ovn/files/9138066/vpc-dns.md)

2022-07-19 07:07 UTC, merged