feat: check configuration
kubeovn/kube-ovn pull request #1832
Opened 2022-08-21 11:20 UTC by lut777

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Features

Now controller will check network CIDRs before initialization, and illegal CIDR will lead to fatal error.

#### Which issue(s) this PR fixes:
Fixes #1813

2022-08-22 12:06 UTC, oilbeater commented
`util/validator.go` has similar logical and should reuse it.

2022-08-23 06:44 UTC, lut777 commented
> `util/validator.go` has similar logical and should reuse it.

It's done.

2022-08-24 02:05 UTC, oilbeater requested changes

2022-08-24 02:05 UTC, oilbeater commented on pkg/controller/config.go
> +	if err := util.CIDRConflict([]string{config.NodeSwitchCIDR, config.DefaultCIDR, config.ServiceClusterIPRange}); err != nil {
cidrCheck 和 conflictCheck 要拆开

2022-08-24 02:05 UTC, oilbeater commented on pkg/util/net.go
> +		if v4 != nil {
不要在 cidrconflict 里检查 cidr 是否正确。否则一个子网非法，其他正常子网都会冲突无法创建

2022-08-24 02:05 UTC, oilbeater commented on pkg/util/net.go
> +func ReturnCidr(address string) (*net.IPNet, *net.IPNet, error) {
```suggestion
func ReturnCidr(cidrBlock string) (*net.IPNet, *net.IPNet, error) {
```

2022-08-24 02:05 UTC, oilbeater commented on pkg/util/net.go
> +	return nil, nil, fmt.Errorf("ip %v unresolvable", address)
```suggestion
	return nil, nil, fmt.Errorf("cidr %v unresolvable", address)
```

2022-08-24 02:05 UTC, oilbeater commented on pkg/util/net.go
> +func checkIPV4(ip *net.IPNet) error {
```suggestion
func checkIPV4Cidr(cidr *net.IPNet) error {
```

2022-08-24 02:05 UTC, oilbeater commented on pkg/util/net.go
> +func checkIPV6(ip *net.IPNet) error {
```suggestion
func checkIPV6Cidr(cidr *net.IPNet) error {
```

2022-08-24 07:03 UTC, lut777 commented on pkg/util/net.go
> +func checkIPV6(ip *net.IPNet) error {
done

2022-08-24 07:03 UTC, lut777 commented on pkg/util/net.go
> +func checkIPV4(ip *net.IPNet) error {
done

2022-08-24 07:03 UTC, lut777 commented on pkg/util/net.go
> +	return nil, nil, fmt.Errorf("ip %v unresolvable", address)
done

2022-08-24 07:03 UTC, lut777 commented on pkg/util/net.go
> +func ReturnCidr(address string) (*net.IPNet, *net.IPNet, error) {
done

2022-08-24 07:04 UTC, lut777 commented on pkg/util/net.go
> +		if v4 != nil {
done

2022-08-24 07:05 UTC, lut777 commented on pkg/controller/config.go
> +	if err := util.CIDRConflict([]string{config.NodeSwitchCIDR, config.DefaultCIDR, config.ServiceClusterIPRange}); err != nil {
两个功能性函数已经拆开, 并且已经根据之前的函数功能重新简化命名并使用.

2022-08-30 07:20 UTC, zhangzujian commented on .github/workflows/build-x86-image.yaml
> +
should be removed

2022-08-30 10:48 UTC, lut777 commented on .github/workflows/build-x86-image.yaml
> +
deleted after debug

2022-08-30 13:34 UTC, oilbeater requested changes

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +func CheckSupCIDROverlap(a, b string) bool {
CheckSupCIDROverlap -> CIDROverlap

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +func CheckCIDRSpec(cidr string) error {
CheckCIDRSpec -> CIDRGlobalUnicast

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +	IPv4bcast            = "255.255.255.255/32"
IPv4Broadcast

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +	IPv4zero             = "0.0.0.0/32"
IPv4Zero

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +	IPv6linkLocalUnicast = "FE80::/10"
All the variables should use camelcase

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with v4 boardcast cidr %s", cidr, IPv4bcast)
broadcast

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with v4 locallink cidr %s", cidr, IPv4LinkLocalUnicast)
link local

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with v6 locallink cidr %s", cidr, IPv6linkLocalUnicast)
link local

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +func CheckCIDRsAll(cidrs []string) error {
CheckCIDRsAll -> CheckSystemCIDR

2022-08-30 13:34 UTC, oilbeater commented on pkg/util/net.go
> +		}
```suggestion
for j := range cidrs {
    if j == i {
       continue
    }
   if CheckSupCIDROverlap(cidr, cidrs[c]) {
       err := fmt.Errorf("cidr %s is conflict with cidr %s", cidr, cidrs[c])
        return err
}
}
```

2022-08-31 08:24 UTC, lut777 commented on pkg/util/net.go
> +func CheckSupCIDROverlap(a, b string) bool {
done

2022-08-31 08:24 UTC, lut777 commented on pkg/util/net.go
> +func CheckCIDRSpec(cidr string) error {
done

2022-08-31 08:25 UTC, lut777 commented on pkg/util/net.go
> +	IPv4bcast            = "255.255.255.255/32"
done

2022-08-31 08:25 UTC, lut777 commented on pkg/util/net.go
> +	IPv4zero             = "0.0.0.0/32"
done

2022-08-31 08:25 UTC, lut777 commented on pkg/util/net.go
> +	IPv6linkLocalUnicast = "FE80::/10"
done

2022-08-31 08:25 UTC, lut777 commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with v4 boardcast cidr %s", cidr, IPv4bcast)
done

2022-08-31 08:25 UTC, lut777 commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with v4 locallink cidr %s", cidr, IPv4LinkLocalUnicast)
done

2022-08-31 08:26 UTC, lut777 commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with v6 locallink cidr %s", cidr, IPv6linkLocalUnicast)
done

2022-08-31 08:26 UTC, lut777 commented on pkg/util/net.go
> +func CheckCIDRsAll(cidrs []string) error {
done

2022-08-31 08:27 UTC, lut777 commented on pkg/util/net.go
> +		}
fixed and done

2022-08-31 08:44 UTC, oilbeater requested changes

2022-08-31 08:44 UTC, oilbeater commented on pkg/util/net.go
> +	IPV4Loopback         = "127.0.0.1/8"
V4 -> v4

2022-08-31 08:44 UTC, oilbeater commented on pkg/util/net.go
> +	IPV6Multicast        = "ff00::/8"
V6 -> v6

2022-08-31 08:44 UTC, oilbeater commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with vv6 multicast cidr %s", cidr, IPV6Multicast)
vv6 -> v6

2022-08-31 08:44 UTC, oilbeater commented on pkg/controller/config.go
> +		return nil, err
klog.Errorf("check system cidr failed, %v", err)

2022-08-31 08:57 UTC, lut777 commented on pkg/util/net.go
> +	IPV4Loopback         = "127.0.0.1/8"
done

2022-08-31 08:58 UTC, lut777 commented on pkg/util/net.go
> +	IPV6Multicast        = "ff00::/8"
done

2022-08-31 08:58 UTC, lut777 commented on pkg/util/net.go
> +			return fmt.Errorf("%s conflict with vv6 multicast cidr %s", cidr, IPV6Multicast)
done

2022-08-31 08:58 UTC, lut777 commented on pkg/controller/config.go
> +		return nil, err
added

2022-08-31 09:24 UTC, oilbeater approved these changes

2022-08-31 09:39 UTC, merged