do not need to delete pg when update networkpolicy
kubeovn/kube-ovn pull request #1959
Opened 2022-10-12 12:06 UTC by hongzhen-ma

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
- Bug fixes

####
do not need to delete pg when update networkpolicy

#### Which issue(s) this PR fixes:
Fixes #1878

2022-10-17 07:01 UTC, oilbeater requested changes

2022-10-17 07:01 UTC, oilbeater commented on pkg/controller/network_policy.go
>  	// before update or add ingress info,we should first delete acl and address_set
the comment should be removed

2022-10-17 07:01 UTC, oilbeater commented on pkg/controller/network_policy.go
>  	// before update or add egress info, we should first delete acl and address_set
same with above

2022-10-17 07:10 UTC, oilbeater approved these changes

2022-10-28 08:05 UTC, hongzhen-ma commented
<img width="1534" alt="企业微信截图_839e2a94-1168-4320-a500-e9f853896aca" src="https://user-images.githubusercontent.com/67130442/198536701-bdc01cd1-51bc-4ea9-9884-cc218ab3bb29.png">

测试确认，不能将 acl 删除放在 acl 创建逻辑中，否则会导致已经创建的 acl 被删除
同时，也不能将删除 acl 的动作去掉，否则会造成 acl 残留

2022-10-31 06:48 UTC, hongzhen-ma commented
测试在同一个 transaction 中，同时执行 删除与添加 acl 的动作，遇到部分情况下，默认添加的 drop 规则没有添加上的情况 
<img width="1621" alt="企业微信截图_40f64d7b-9e43-422d-9edd-bd6855264212" src="https://user-images.githubusercontent.com/67130442/198947869-6f801118-df91-4210-8382-c461e7ac1b9a.png">

命令行确认是正确的，手动执行的话，就有 drop 规则生成

2022-10-31 07:19 UTC, hongzhen-ma commented
1、删除 acl 的动作，只能在循环外执行一次，删除之后，就只能执行添加的动作。
否则可能在循环的下次操作中，将上次创建的acl 删除掉。双栈的情况，在执行 v6 acl 创建的时候，会将 v4 acl 删除掉
2、删除与创建动作，要分开执行。存在时序冲突的问题，参考上边截图示例。

2022-11-01 05:15 UTC, hongzhen-ma commented
如果将 drop ACL的 --may-exist 去掉，就会在创建 acl 时候出现冲突
<img width="1620" alt="企业微信截图_21b75932-f7e9-488e-ad87-414debd7ec1d" src="https://user-images.githubusercontent.com/67130442/199163779-0111454a-b9d7-45fa-ad2f-f893225efaab.png">

2022-11-02 06:33 UTC, hongzhen-ma commented
使用--id 指定 acl 参数，创建acl，在同一个transaction的命令行中，指定的 --id 参数不能重复，否则有以下报错
<img width="1624" alt="企业微信截图_a787e227-6122-49d2-b9f9-8c4b31774565" src="https://user-images.githubusercontent.com/67130442/199415484-56e217c8-f321-4f8b-901d-eb7225cc0c91.png">

2022-11-02 10:33 UTC, oilbeater approved these changes

2022-11-02 12:26 UTC, merged