add helm and e2e test
kubeovn/kube-ovn pull request #2020
Opened 2022-11-07 08:42 UTC by lut777

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Features

#### Which issue(s) this PR fixes:
Fixes #2007

2022-11-14 02:11 UTC, oilbeater requested changes

2022-11-14 02:11 UTC, oilbeater commented on kubeovn-helm/values.yaml
> +perform:
```suggestion
performance:
```

2022-11-14 02:11 UTC, oilbeater commented on kubeovn-helm/values.yaml
> +  LOGICAL_GATEWAY: false
not belong to cni_conf

2022-11-14 02:11 UTC, oilbeater commented on kubeovn-helm/values.yaml
> +affinity: {}
not needed

2022-11-14 02:11 UTC, oilbeater commented on kubeovn-helm/values.yaml
> +  #  - secretName: chart-example-tls
not needed

2022-11-14 14:41 UTC, lut777 commented on kubeovn-helm/values.yaml
> +perform:
fixed.

2022-11-14 14:42 UTC, lut777 commented on kubeovn-helm/values.yaml
> +  #  - secretName: chart-example-tls
deleted.

2022-11-15 09:07 UTC, oilbeater requested changes

2022-11-15 09:07 UTC, oilbeater commented on dist/images/install.sh
> -metadata:
why delete this?

2022-11-15 09:07 UTC, oilbeater commented on kubeovn-helm/values.yaml
> +  tunnel_type: geneve
Use all capital or lower case letters

2022-11-15 10:10 UTC, lut777 commented on Makefile
> +.PHONY: kind-untaint-control-plane
deleted

2022-11-15 10:11 UTC, lut777 commented on dist/images/install.sh
> -metadata:
find duplicated

2022-11-15 10:15 UTC, lut777 commented on kubeovn-helm/values.yaml
> +  tunnel_type: geneve
fixed.

2022-11-15 11:16 UTC, oilbeater approved these changes

2022-11-16 01:58 UTC, merged