ovn eip snat fip
kubeovn/kube-ovn pull request #2029
Opened 2022-11-09 12:38 UTC by bobz965

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

support vpc use ovn eip fip snat  by crd , compatiblewith  provider network, vlan, subnet, compatible with previous default vpc  enable_eip_snat

#### What type of this PR
- Features

2022-11-09 12:39 UTC, bobz965 commented
[10-support-ovn-eip-fip-snat-draft.md](https://github.com/kubeovn/kube-ovn/files/9971076/10-support-ovn-eip-fip-snat-draft.md)

2022-11-10 09:57 UTC, bobz965 commented
test previous ovn-default default vpc enable eip fip works well and not changed:
[01-test-kube-ovn-eip-snat-ovn-default-vpc-as-previous.txt](https://github.com/kubeovn/kube-ovn/files/9979535/01-test-kube-ovn-eip-snat-ovn-default-vpc-as-previous.txt)

2022-11-15 03:52 UTC, hongzhen-ma requested changes

2022-11-15 03:52 UTC, hongzhen-ma commented on pkg/controller/ovn_eip.go
> +		return err
加个log比较好

2022-11-15 03:52 UTC, hongzhen-ma commented on pkg/controller/ovn_eip.go
> +			return err
这也加个log吧

2022-11-15 03:52 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +	if err := c.handleDelVpcExternal(vpc.Name); err != nil {
也加个log

2022-11-15 03:52 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +		if v4ip, v6ip, mac, err = c.acquireIpAddress(c.config.ExternalGatewaySwitch, lrpEipName, lrpEipName); err != nil {
申请地址失败，也加个log吧

2022-11-15 03:52 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +	if err := c.ovnLegacyClient.ConnectRouterToExternal(c.config.ExternalGatewaySwitch, key, v4ipCidr, mac, chassises); err != nil {
关键配置报错，也加个log吧

2022-11-15 03:52 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +	if err := c.ovnLegacyClient.DisconnectRouterToExternal(c.config.ExternalGatewaySwitch, key); err != nil {
这个地方也加一下log

2022-11-15 07:34 UTC, merged