libovsdb: set tcp socket timeout to 10s
kubeovn/kube-ovn pull request #2070
Opened 2022-11-22 09:40 UTC by zhangzujian

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR

- Bug fixes

#### Which issue(s) this PR fixes:
 After a power/network failure, the libovsdb client cannot communicate with the ovn nb leader anymore. This causes the client-side TCP connection to be stuck for a long time.

By setting the TCP socket timeout, the client will be able to close the connection and try to connect to other servers.

2022-11-22 09:42 UTC, zhangzujian commented
Reference: https://github.com/golang/go/issues/31490#issuecomment-544140457

2022-11-23 03:26 UTC, zhangzujian commented
libovsdb patch: https://github.com/kubeovn/libovsdb/commit/3e352fe182635596163b74eac7f84b8ab88eff17

2022-11-23 03:48 UTC, oilbeater requested changes

2022-11-23 03:48 UTC, oilbeater commented on go.mod
> +	github.com/kubeovn/libovsdb v0.0.0-20221123021657-3e352fe18263
we can use go mod replace to point to a new path and avoid all the import rename

2022-11-23 06:30 UTC, oilbeater approved these changes

2022-11-27 03:21 UTC, oilbeater approved these changes

2022-11-27 07:43 UTC, merged