refactor e2e testing - part 1
kubeovn/kube-ovn pull request #2078
Opened 2022-11-24 06:29 UTC by zhangzujian

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR

- Tests

#### Which issue(s) this PR fixes:
This is part of the work for #1883.

2022-12-27 07:03 UTC, oilbeater requested changes

2022-12-28 09:53 UTC, zhangzujian commented on .github/workflows/build-x86-image.yaml
> +  installation-compatibility-test:
Test installation for k8s prior to v1.24.

The master label is no longer present on kubeadm control plane. For new clusters, the label 'node-role.kubernetes.io/master' will no longer be added to control plane nodes, only the label 'node-role.kubernetes.io/control-plane' will be added.

2022-12-28 10:00 UTC, zhangzujian commented
@oilbeater  Please review.

2022-12-29 01:58 UTC, oilbeater approved these changes

2022-12-29 02:16 UTC, merged