fix: ecmp route keep delete and recreate
kubeovn/kube-ovn pull request #2083
Opened 2022-11-25 11:35 UTC by bobz965

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Bug fixes

Fixes #2066

2022-11-29 04:29 UTC, hongzhen-ma requested changes

2022-11-29 04:29 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +			// 0 subnet v4 cidr
这个注释有必要吗？

2022-11-29 04:29 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +	if vpc.Spec.PolicyRoutes != nil {
如果是把vpc.spec. PolicyRoutes 删掉呢？这里怎么处理？

2022-11-29 04:30 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +				if err = c.updatePolicyRouteForCentralizedSubnet(subnet.Name, subnet.Spec.CIDRBlock, nodeIPs, nameIpMap); err != nil {
原来的 add 函数内，有策略路由是否存在的检查，如果存在，就不再重复创建。update 没有检测，是会先删除再创建，这个替换是必要的吗？

2022-11-29 06:19 UTC, bobz965 commented on pkg/controller/subnet.go
> +				if err = c.updatePolicyRouteForCentralizedSubnet(subnet.Name, subnet.Spec.CIDRBlock, nodeIPs, nameIpMap); err != nil {
原来的执行方式会把策略路由重新更新一遍，因为nodeIPs参数是多个node的ip列表，而不是一个node的v4ip,v6ip

2022-11-29 06:45 UTC, bobz965 commented on pkg/controller/init.go
> +		if node.Annotations[util.AllocatedAnnotation] == "true" {
这里还原，下面单独策略路由操作的时候，避免删除重建的操作

2022-12-01 01:55 UTC, hongzhen-ma requested changes

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +			if subnet.Spec.GatewayNode != "" {
在分布式子网的入口，将 subnet.Spec.GatewayNode 设置为空了，这里加检查，应该是无法满足条件。需要确认下从分布式子网，切换成集中式子网，确实将集中式子网策略路由删掉了

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +							if index == 0 {
不能完全依赖index 来确定顺序，可以调用 util.CheckProtocol 来检查 IP 实际的类型

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +					if index == 0 {
同样不能依赖 index 来确定类型

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +				if nodeV6Ips != nil && v6Cidr != "" {
感觉没有必要区分开 IPv4 和 IPv6 分别处理。在原来的基础上，不能做策略路由存在的校验吗？

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +				// use vpc spc policy to control policy route diff update
这一行注释没看明白

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> -
子网切换成集中式子网之后，删除原来分布式策略路由的动作，为什么要删除？

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/ovs/ovn-nbctl-legacy.go
> +		klog.Infof("remove inconsistent policy route from router %s: match %s", router, match)
上边的 if 有效的话，这个判断是不是就可以省略了？

2022-12-01 01:55 UTC, hongzhen-ma commented on pkg/ovs/ovn-nbctl-legacy.go
> +			outputNexthops, err := c.ovnNbCommand("--data=bare", "--no-heading", "--columns=nexthops", "list", "Logical_Router_Policy", r)
可以看下  CustomFindEntity  接口的使用，一次查询出策略路由要校验的参数

2022-12-02 01:53 UTC, hongzhen-ma approved these changes

2022-12-02 03:40 UTC, zhangzujian commented on pkg/controller/subnet.go
> +							}
```suggestion
						nexthopV4, nexthopV6 := util.SplitStringIP(nexthopNodeIP)
						if nexthopV4 != "" {
							nameV4IpMap[node.Name] = nexthopV4
							nodeV4Ips = append(nodeV4Ips, nexthopV4)
						}
						if nexthopV6 != "" {
							nameV6IpMap[node.Name] = nexthopV6
							nodeV6Ips = append(nodeV6Ips, nexthopV6)
						}
```

2022-12-02 03:41 UTC, zhangzujian commented on pkg/util/const.go
> +	GatewayECMPPolicyPriority   = 29000
We should use `GatewayRouterPolicyPriority` in stead.

2022-12-02 03:47 UTC, zhangzujian commented on pkg/controller/subnet.go
>  				for _, gw := range strings.Split(subnet.Spec.GatewayNode, ",") {
```suggestion
				gatewayNodes := strings.Split(subnet.Spec.GatewayNode, ",")
				nodeV4Ips := make([]string, 0, len(gatewayNodes))
				nodeV6Ips := make([]string, 0, len(gatewayNodes))
				nameV4IpMap := make(map[string]string, len(gatewayNodes)*2)
				nameV6IpMap := make(map[string]string, len(gatewayNodes)*2)
				for _, gw := range gatewayNodes {
```

2022-12-02 03:49 UTC, zhangzujian commented on pkg/controller/subnet.go
> +				}
```suggestion
				v4Cidr, v6Cidr := util.SplitStringIP(subnet.Spec.CIDRBlock)
```

2022-12-02 06:19 UTC, zhangzujian approved these changes

2022-12-02 07:26 UTC, merged