add flows to map pkt_mark to vlan priority
kubeovn/kube-ovn pull request #2230
Opened 2023-01-06 07:13 UTC by hongzhen-ma

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

- Features

#### Which issue(s) this PR fixes:
Fixes #2215

2023-01-09 03:19 UTC, oilbeater requested changes

2023-01-09 03:19 UTC, oilbeater commented on pkg/ovs/ovs-ofctl.go
> +func ParseDumpFlowsOutput(output string) []string {
Add a ut for this function

2023-01-10 01:25 UTC, oilbeater commented
Need backport to 1.9

2023-01-10 02:57 UTC, hongzhen-ma commented on pkg/ovs/ovs-ofctl.go
> +func ParseDumpFlowsOutput(output string) []string {
modified

2023-01-17 08:28 UTC, closed without merging

2023-01-17 08:29 UTC, hongzhen-ma commented
经过验证，确认在容器网络中，无法匹配 pkt_mark 参数过滤流表