perform the gateway check but ignore the result when the annotation of subnet is ‘disableGatewayCheck=true’ to make sure of the first network packet
kubeovn/kube-ovn pull request #2290
Opened 2023-02-05 14:41 UTC by qiutingjun

- Features

Under the underlay network mode, there are many situations will cause the underlay network arping fails, so there is a highly probability of gateway check failure.
If the gateway check is not performed, the pod or vm cannot be pinged from the outside after it is pulled up, because of there is no first network packet.
So I expect the gateway check is still performed but the result does not concerned when the annotation of subnet is ‘disableGatewayCheck=true’.

2023-02-06 02:14 UTC, oilbeater commented
The `waitNetworkReady` will try 200 times before timeout. If only need to send a first packet, we should not run the probe 200 times. `kube-ovn-cni` will hold a goroutine for each unfinished probe and it will also send lots of unnecessary packets into underlay network.

2023-02-06 15:58 UTC, qiutingjun commented
> The `waitNetworkReady` will try 200 times before timeout. If only need to send a first packet, we should not run the probe 200 times. `kube-ovn-cni` will hold a goroutine for each unfinished probe and it will also send lots of unnecessary packets into underlay network.

Thank you for reminding me about the setting of retry times，and I've added a parameter to control the max retries.

2023-02-09 02:25 UTC, oilbeater approved these changes

2023-02-09 02:28 UTC, oilbeater requested changes

2023-02-09 02:28 UTC, oilbeater commented on pkg/daemon/ovs_linux.go
> +		return nil
The waitNetworkReady with only one probe should return fast enough. No need to run in a goroutine and it will lead the lint error

2023-02-13 02:02 UTC, oilbeater approved these changes

2023-02-13 02:02 UTC, merged

2023-02-13 02:02 UTC, oilbeater commented
Thanks! @qiutingjun