fix github actions workflows
kubeovn/kube-ovn pull request #2363
Opened 2023-02-20 07:05 UTC by zhangzujian

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR

- CI

#### Which issue(s) this PR fixes:
Fixes #(issue-number)

2023-02-21 09:45 UTC, oilbeater requested changes

2023-02-21 09:45 UTC, oilbeater commented on .github/workflows/codeql-analysis.yml
> +    - name: Build
Still takes 19min without cache

2023-02-21 10:11 UTC, zhangzujian commented on .github/workflows/codeql-analysis.yml
> +    - name: Build
CodeQL does not support cache.

2023-02-22 02:55 UTC, oilbeater approved these changes

2023-02-22 05:32 UTC, merged