Support bfd management
kubeovn/kube-ovn pull request #2382
Opened 2023-02-24 13:59 UTC by bobz965

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

[15-kube-ovn-ecmp-with-bfd.md](https://github.com/kubeovn/kube-ovn/files/10824869/15-kube-ovn-ecmp-with-bfd.md)

2023-02-28 05:46 UTC, hongzhen-ma requested changes

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +		return nil
不能 return nil，还需要继续后面的处理

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +		return nil
同样，不能 return nil

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +		if !k8serrors.IsNotFound(err) {
add log

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +		}
not  found 的情况，也需要处理

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +		}
not found 情况

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +			klog.Errorf("failed to reconcile vpc %q bfd static route", vpc.Name)
return err ?

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +				klog.Errorf("failed to reconcile del vpc %q normal static route", vpc.Name)
return err ?

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/controller/vpc.go
> +				klog.Errorf("failed to reconcile vpc %q bfd static route", vpc.Name)
return err?

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/ovs/ovn-nbctl-legacy.go
> +				ECMP:    fields[4],
4 or 3 ?

2023-02-28 05:46 UTC, hongzhen-ma commented on pkg/ovs/ovn-nbctl-legacy.go
> +		klog.Errorf("faild to create bfd for lrp %q dst ip %q, output %s, %v", lrp, dstIp, output, err)
%q ?

2023-02-28 05:52 UTC, bobz965 commented on pkg/controller/config.go
> +		argBfdDetectMult = pflag.Int("detect-mult", 3, "The negotiated transmit interval, multiplied by this value, provides the Detection Time for thereceiving system in Asynchronous mode.")
ok

2023-02-28 05:52 UTC, bobz965 commented on pkg/controller/subnet.go
> +		return nil
ok

2023-02-28 05:52 UTC, bobz965 commented on pkg/controller/subnet.go
> +		return nil
ok

2023-02-28 05:53 UTC, bobz965 commented on pkg/controller/subnet.go
> +		if !k8serrors.IsNotFound(err) {
ok

2023-02-28 05:56 UTC, bobz965 commented on pkg/controller/subnet.go
> +		}
ok

2023-02-28 06:00 UTC, bobz965 commented on pkg/controller/subnet.go
> +			klog.Errorf("failed to reconcile vpc %q bfd static route", vpc.Name)
ok

2023-02-28 06:02 UTC, bobz965 commented on pkg/controller/vpc.go
> +				klog.Errorf("failed to reconcile del vpc %q normal static route", vpc.Name)
ok

2023-02-28 06:02 UTC, bobz965 commented on pkg/controller/vpc.go
> +				klog.Errorf("failed to reconcile vpc %q bfd static route", vpc.Name)
ok

2023-02-28 06:05 UTC, bobz965 commented on pkg/ovs/ovn-nbctl-legacy.go
> +				ECMP:    fields[4],
是 4

[root@pc-node-1 03-cust-vpc]# k ko nbctl lr-route-list vpc1
IPv4 Routes
Route Table <main>:
           192.168.0.0/24              10.5.204.104 src-ip ecmp ecmp-symmetric-reply bfd
           192.168.0.0/24              10.5.204.114 src-ip ecmp ecmp-symmetric-reply bfd
           192.168.0.0/24              10.5.204.124 src-ip ecmp ecmp-symmetric-reply bfd

2023-02-28 06:06 UTC, bobz965 commented on pkg/ovs/ovn-nbctl-legacy.go
> +		klog.Errorf("faild to create bfd for lrp %q dst ip %q, output %s, %v", lrp, dstIp, output, err)
ok

2023-03-01 02:18 UTC, hongzhen-ma approved these changes

2023-03-01 02:49 UTC, merged