feat: add support for EIP QoS
kubeovn/kube-ovn pull request #2550
Opened 2023-03-24 14:58 UTC by shane965

1. Create a QoSPolicy CRD and manage its lifecycle.
2. Add a new "spec.qosPolicy" field to iptablesEIP to relate to the QoSPolicy.
3. Configure NATGW EIP QoS when "spec.qosPolicy" changes.
4. Implement NATGW EIP QoS functionality using Linux TC.

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
- Features

#### Which issue(s) this PR fixes:
Fixes #2496

2023-03-27 01:36 UTC, bobz965 commented on dist/images/cleanup.sh
> +                                      ovn-eips.kubeovn.io ovn-fips.kubeovn.io ovn-snat-rules.kubeovn.io \ qos-policies.kubeovn.io
去掉 \  或者单独放到下面一行

2023-03-27 01:38 UTC, bobz965 commented on dist/images/vpcnatgateway/nat-gateway.sh
> +        tc -p -s -d filter show dev net1 parent $qdisc_id prio 1 | grep $v4ip
grep -w $v4ip  不然可能只匹配部门，而不是完整ip

2023-03-27 01:57 UTC, bobz965 requested changes

2023-03-27 01:57 UTC, bobz965 commented on dist/images/vpcnatgateway/nat-gateway.sh
> +        tc -p -s -d filter show dev net1 parent $qdisc_id prio 1 | grep $v4ip
grep -w

2023-03-27 01:57 UTC, bobz965 commented on dist/images/vpcnatgateway/nat-gateway.sh
> +        tc -p -s -d filter show dev net1 parent $qdisc_id prio 1 | grep $v4ip
grep -w

2023-03-27 01:57 UTC, bobz965 commented on dist/images/vpcnatgateway/nat-gateway.sh
> +        tc -p -s -d filter show dev net1 parent $qdisc_id prio 1 | grep $v4ip
grep -w

2023-03-27 01:57 UTC, bobz965 commented on dist/images/vpcnatgateway/nat-gateway.sh
> + eip-ingress-qos-set)
采用add del作为方法命名后缀，保持一致，比set del更好一些

2023-03-27 01:57 UTC, bobz965 commented on pkg/apis/kubeovn/v1/status.go
> +func (qs *QoSPolicyStatus) Bytes() ([]byte, error) {
qos 比qs更好些

2023-03-27 01:57 UTC, bobz965 commented on pkg/apis/kubeovn/v1/types.go
> +	QoSPolicyUpdated string `json:"qosPolicyUpdated" patchStrategy:"merge"`
这个是否可以放到Ready的判断逻辑中？

2023-03-27 01:57 UTC, bobz965 commented on pkg/controller/qos_policy.go
> +		eips, err := c.config.KubeOvnClient.KubeovnV1().IptablesEIPs().List(context.Background(), metav1.ListOptions{})
引入一个qos=key的label，比过滤所有要更好些

2023-03-27 01:57 UTC, bobz965 commented on pkg/controller/vpc_nat_gw_eip.go
> +// delEipQoS deletes Quality of Service settings for an external IP (EIP) in the natgw pod using tc.
delete tc rule  for eip in  nat gw pod

2023-03-27 01:57 UTC, bobz965 commented on pkg/controller/vpc_nat_gw_eip.go
> +
// del ingress qos

2023-03-28 00:59 UTC, shane965 commented on pkg/apis/kubeovn/v1/types.go
> +	QoSPolicyUpdated string `json:"qosPolicyUpdated" patchStrategy:"merge"`
`QoSPolicyUpdated`这个字段目前没有使用场景，我已经去掉了

2023-03-28 02:31 UTC, bobz965 commented on pkg/apis/kubeovn/v1/types.go
> +	Ready              bool                        `json:"ready" patchStrategy:"merge"`
qos policy 的ready 以及 redo是否是有意义的？ qos是被引用的对象，只存储qos规则。ready和redo是否已包含于eip的ready以及redo流程？

2023-03-28 02:31 UTC, bobz965 commented on pkg/controller/qos_policy.go
> +	if cachedQoS.Status.Ready {
如果去掉了Ready 这里可以基于status和spec的属性比较来判断

2023-03-28 02:46 UTC, bobz965 commented on pkg/apis/kubeovn/v1/types.go
> +	Ready              bool                        `json:"ready" patchStrategy:"merge"`
感觉需要再讨论下，可能可以去掉

2023-03-28 03:48 UTC, shane965 commented on pkg/apis/kubeovn/v1/types.go
> +	Ready              bool                        `json:"ready" patchStrategy:"merge"`
去掉吧，后面有用到的场景再加，避免出现太多冗余的字段

2023-03-28 05:34 UTC, bobz965 approved these changes

2023-04-03 02:22 UTC, bobz965 commented on dist/images/vpcnatgateway/nat-gateway.sh
> -            exec_cmd "tc filter del dev net1 parent $qdisc_id protocol ip prio 1 u32 match ip dst $v4ip"
tc -p -s -d filter show dev net1 parent $qdisc_id prio 1 | grep -w $v4ip
        if [ "$?" -eq 0 ];then
            exec_cmd "tc filter del dev net1 parent $qdisc_id protocol ip prio 1 u32 match ip dst $v4ip"

移除旧的没在用删除判定逻辑  考虑补充下新的删除判定逻辑相关注释

2023-04-03 03:28 UTC, bobz965 approved these changes

2023-04-04 02:29 UTC, bobz965 approved these changes

2023-04-06 01:15 UTC, shane965 commented
@hongzhen-ma , could you review my code? Thank you!

2023-04-10 07:08 UTC, hongzhen-ma commented on pkg/controller/vpc_nat_gw_eip.go
> +
多余空行，可以删掉

2023-04-10 07:08 UTC, hongzhen-ma commented on pkg/controller/vpc_nat_gw_eip.go
> +	var addRules []string
delRules 是不是更合适些？这个问题不大，不改也没影响

2023-04-10 09:48 UTC, shane965 commented on docs/eip-qos.md
> +# EIP QoS
嗯嗯，我后面单独提交一份到docs仓库

2023-04-10 10:39 UTC, hongzhen-ma approved these changes

2023-04-10 10:50 UTC, merged