feat:  suport kubevirt nic hotplug
kubeovn/kube-ovn pull request #3013
Opened 2023-07-05 02:30 UTC by watermelon-brother

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

### What type of this PR
- Features

kubevirt hotplug interface will cause kube-ovn create veth-pair.

2023-07-10 06:04 UTC, oilbeater commented
The lint error should be fixed

2023-07-12 02:37 UTC, oilbeater requested changes

2023-07-12 02:37 UTC, oilbeater commented on pkg/daemon/ovs_linux.go
> +	if strings.HasPrefix(ifname, "pod") {
can you give an comment about why in some scenario the ifname will has prefix `pod` and exceed the length.

2023-07-12 03:05 UTC, oilbeater approved these changes

2023-07-12 03:06 UTC, merged

2023-07-12 03:06 UTC, oilbeater commented
Thanks! @watermelon-brother

2023-07-13 10:03 UTC, bobz965 commented
backport "if" name starts with pod logic to release 1.11