fix:  lsp define in nb is not clear when delete vm
kubeovn/kube-ovn pull request #3429
Opened 2023-11-16 07:03 UTC by watermelon-brother

## What type of this PR

fix:  lsp define in nb is not clear when delete vm

## Which issue(s) this PR fixes

lsp define is not clear in nb

## WHAT

If lsp define in nb is not clear, only gc run can clear it.

## HOW

we can think the pod is vm or normal pod when add some logic.

2023-11-16 07:09 UTC, bobz965 approved these changes

2023-11-17 08:15 UTC, hongzhen-ma requested changes

2023-11-17 08:15 UTC, hongzhen-ma commented on pkg/controller/pod.go
> +	if isVMPod {
在设置 keep-vm-ip 参数的情况下，可以使用 vm name 作为 key 查找 lsp
如果没有设置该参数，vm pod 的 lsp name 仍然为 pod name 构成。

因此需要添加  c.config.EnableKeepVMIP 参数判断

2023-11-17 10:01 UTC, watermelon-brother commented on pkg/controller/pod.go
> +	if isVMPod {
ok

2023-11-28 07:03 UTC, bobz965 commented on pkg/controller/pod.go
> +	if isVMPod {
pod ipam release 也需要修改下名字

2023-11-30 02:32 UTC, bobz965 commented
pr #3476 has fixed this.

2023-11-30 02:32 UTC, closed without merging