u2o: add policy route for service when disabling lb
kubeovn/kube-ovn pull request #3813
Opened 2024-03-08 05:47 UTC by zcq98

# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-03-11 01:18 UTC, bobz965 commented on pkg/controller/subnet.go
> +			if !c.config.EnableLb {
考虑两个 if !c.config.EnableLb { 合并逻辑

2024-03-11 01:18 UTC, bobz965 commented on pkg/controller/subnet.go
> +					klog.Infof("delete u2o port group %s for subnet %s", pg.Name, subnet.Name)
```suggestion
					klog.Infof("failed to delete u2o port group %s for subnet %s", pg.Name, subnet.Name)
```

2024-03-11 01:18 UTC, bobz965 commented on pkg/controller/subnet.go
> +		if subnet.Spec.Vpc == c.config.ClusterRouter && !c.config.EnableLb {
```suggestion
		if  !c.config.EnableLb && subnet.Spec.Vpc == c.config.ClusterRouter {
```

2024-03-12 01:06 UTC, zcq98 commented on pkg/controller/subnet.go
> +					klog.Infof("delete u2o port group %s for subnet %s", pg.Name, subnet.Name)
这个日志是开始删除 port group，不是删除失败

2024-03-12 01:45 UTC, zhangzujian commented
There is another `enableLb` filed in subnet definition: `.spec.enableLb`.

2024-03-12 09:28 UTC, zcq98 commented
> There is another `enableLb` filed in subnet definition: `.spec.enableLb`.

1、关闭全局 LB，子网级别 LB 会失效，此时需要下发策略路由保证开启 U2O 后 Underlay Pod 能访问 Service
2、开启全局 LB，若子网关闭了自身的 LB，则仍会出现开启 U2O 后无法访问 Service 的问题
因此考虑在开启 U2O 后无论是否开启 LB 都下发策略路由，当 LB 开启后，访问 Service 走 LB，不会再匹配策略路由，关闭 LB 时，访问 Service 走策略路由，经 ovn0 访问 Service

2024-03-12 09:41 UTC, bobz965 requested changes

2024-03-12 09:41 UTC, bobz965 commented on pkg/controller/subnet.go
> +		if !c.config.EnableLb && subnet.Spec.Vpc == c.config.ClusterRouter {
判断 u2o

2024-03-12 09:44 UTC, zcq98 commented on pkg/controller/subnet.go
> +		if !c.config.EnableLb && subnet.Spec.Vpc == c.config.ClusterRouter {
这里的逻辑已经在 u2o 开启的里了，只需要把 !c.config.EnableLb 去掉就行

2024-03-12 09:44 UTC, zcq98 commented on pkg/controller/subnet.go
> +		if !c.config.EnableLb && subnet.Spec.Vpc == c.config.ClusterRouter {
已修正

2024-03-12 09:47 UTC, bobz965 approved these changes

2024-03-13 02:21 UTC, zhangzujian commented
We should check whether ovn lb is enabled or not before creating the logical router policy.

2024-03-13 09:00 UTC, zcq98 commented
> We should check whether ovn lb is enabled or not before creating the logical router policy.

Service 的 backends 不一定是 ovn-default 下的 Pods，来一个 Service 判断一下 backends 所在的子网是否开启  LB 似乎不太合适

2024-03-20 02:09 UTC, zcq98 commented
hi @zhangzujian，could you help review this？

2024-03-20 02:23 UTC, merged

2024-03-20 03:12 UTC, bobz965 commented
> We should check whether ovn lb is enabled or not before creating the logical router policy.

it looks already done.