subnet re calculate
kubeovn/kube-ovn pull request #3911
Opened 2024-04-12 07:23 UTC by bobz965

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/b971c160-ae87-4833-bcda-a1ff86c81165)

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/8bf80f44-b977-4c7d-ac45-932d7f5c2535)

可能存在ip正在删除中，但是识别每一个ip是否都在删除中也是一个O(n)的开销，所以遇到这种情况，先重算一下。

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-04-12 08:58 UTC, bobz965 commented
hi @zhangzujian , please help review, thanks!

2024-04-12 10:55 UTC, zhangzujian commented on dist/images/check-kube-ovn-restarts.sh
> +  exit 1
What's the purpose of this script? Why `exit 1` here?

2024-04-12 10:58 UTC, zhangzujian commented on pkg/controller/subnet.go
> +		err := fmt.Errorf("subnet %s has v4 using ip, but v4 using ip range is empty", subnet.Name)
```suggestion
		err := fmt.Errorf("subnet %s has %d v4 ip in use, while the v4 using ip range is empty", subnet.Name)
```

2024-04-12 11:01 UTC, zhangzujian requested changes

2024-04-12 11:01 UTC, zhangzujian commented on pkg/controller/subnet.go
> +		klog.Errorf("perhaps subnet %s has some ips in deleting: %v", subnet.Name, err)
```suggestion
		klog.Errorf("inconsistency detected in status of subnet %s : %v", subnet.Name, err)
```

2024-04-15 02:14 UTC, bobz965 commented on dist/images/check-kube-ovn-restarts.sh
> +  exit 1
我们最近发现 多公网相关的 e2e 可能会导致 ovn-central pod 崩溃重启，所以加一个检查脚本，如果发现 pod 重启过，则认为 e2e 是失败的。用于在 cleanup 前执行。

2024-04-15 02:28 UTC, zhangzujian commented on dist/images/check-kube-ovn-restarts.sh
> +  exit 1
我建议在 ci 中加一个步骤，放到 e2e 之后，专门用于检查 kube-ovn 的 Pod 是否有过预期之外的 crash 或者重启。如果有过重启，就用 kubectl ko log 收集日志。

2024-04-15 02:29 UTC, zhangzujian commented on dist/images/check-kube-ovn-restarts.sh
> +  exit 1
这个 ci 的步骤最好做成通用的，然后把它也放到其它 e2e workflow 里。

2024-04-16 05:37 UTC, closed without merging