refactor ipsec function
kubeovn/kube-ovn pull request #4334
Opened 2024-07-24 08:02 UTC by changluyi

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-07-24 08:15 UTC, zhangzujian commented
Could you lease add an e2e test case for this feature? I'm working on [security: run as non-root user](https://github.com/kubeovn/kube-ovn/pull/4326), which may break this function.

2024-07-24 08:27 UTC, changluyi commented
> Could you please add an e2e test case for this feature? I'm working on [security: run as non-root user](https://github.com/kubeovn/kube-ovn/pull/4326), which may break this function.

e2e case will be added

2024-07-31 05:40 UTC, zhangzujian commented on Makefile
> +		ENABLE_OVN_IPSEC=true bash
```suggestion
.PHONY: kind-install-ovn-ipsec
kind-install-ovn-ipsec:
	@$(MAKE) ENABLE_OVN_IPSEC=true kind-install
```

2024-08-02 02:46 UTC, oilbeater requested changes

2024-08-02 02:46 UTC, oilbeater commented on pkg/controller/controller.go
> +	csrLister           certListerv1.CertificateSigningRequestLister
need a empty line to separate.

2024-08-03 12:19 UTC, changluyi commented on pkg/controller/controller.go
> +	csrLister           certListerv1.CertificateSigningRequestLister
1

2024-08-03 12:19 UTC, changluyi commented on Makefile
> +		ENABLE_OVN_IPSEC=true bash
1

2024-08-12 01:36 UTC, oilbeater approved these changes

2024-08-12 01:38 UTC, merged

2024-08-12 05:38 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:39 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:40 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:40 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:40 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:41 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:41 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err := c.updateCsrStatus(csr); err != nil {
need log err

2024-08-12 05:41 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err := c.updateCsrStatus(csr); err != nil {
need log err

2024-08-12 05:41 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:41 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:42 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:42 UTC, bobz965 commented on pkg/controller/signer.go
> +	if block == nil || block.Type != "CERTIFICATE REQUEST" {
need log err

2024-08-12 05:42 UTC, bobz965 commented on pkg/controller/signer.go
> +		err := errors.New("PEM block type must be CERTIFICATE")
need log err

2024-08-12 05:42 UTC, bobz965 commented on pkg/controller/signer.go
> +		fmt.Println(block.Type)
need log err

2024-08-12 05:42 UTC, bobz965 commented on pkg/controller/signer.go
> +	if err != nil {
need log err

2024-08-12 05:42 UTC, bobz965 commented on pkg/controller/signer.go
> +		if err := pem.Encode(&b, &pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw}); err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +		if os.IsNotExist(err) {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if _, err := c.config.KubeClient.CertificatesV1().CertificateSigningRequests().Create(context.Background(), csr, metav1.CreateOptions{}); err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +		if err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +	if err := os.MkdirAll(ipsecKeyDir, 0o755); err != nil {
need log err

2024-08-12 05:46 UTC, bobz965 commented on pkg/daemon/ipsec.go
> +		if err != nil {
need log err

2024-08-12 05:47 UTC, bobz965 commented
@changluyi 大佬，我感觉有些err log 还是就近打印更好些，后面有空麻烦补充下