[fix]: delete the NIC regardless of whether the Pod was found or not.
kubeovn/kube-ovn pull request #4500
Opened 2024-09-10 10:48 UTC by liyh-yusur

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Describe 
当删除pod时，若pod被直接删除cni来不及处理时，通过`pod, err := csh.Controller.podsLister.Pods(podRequest.PodNamespace).Get(podRequest.PodName)`获取pod进行后续的处理条件，会导致此时无法处理，直接在`k8serrors.IsNotFound`中返回。

##  复现
例如 在pod的部署yaml中设置了terminationGracePeriodSeconds: 0，导致 Pod 在删除 Deployment 后被立即终止，而 CNI 插件的 handleDel 函数还没来得及处理删除网卡的操作。
使用 podRequest.ContainerID 来识别 Pod，而不是使用 podRequest.PodName。这样即使 Pod 已经被删除，CNI 插件仍然可以通过容器 ID 来删除网卡。
```bash
    spec:
      containers:
      - name: iperf3-server
        image: harbor.yusur.tech/yusur_ovn/iperf3
        args: ['-s','-p','5001']
        resources:
            requests:
              yusur.tech/sriov_dpu: '1'
            limits:
              yusur.tech/sriov_dpu: '1'
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0
      nodeSelector:
        app: node1
```

2024-09-14 02:57 UTC, bobz965 commented on pkg/daemon/handler.go
> +			nicType = "veth-pair"
感觉像上面那样用个常量，用 nicType = util.VethType 会更好些

2024-09-14 09:51 UTC, liyh-yusur commented on pkg/daemon/handler.go
> +			nicType = "veth-pair"
已经改成了常量

2024-09-16 05:36 UTC, bobz965 approved these changes

2024-09-17 12:10 UTC, oilbeater requested changes

2024-09-17 12:10 UTC, oilbeater commented on pkg/daemon/ovs_windows.go
> +func (csh cniServerHandler) deleteNic(podName, podNamespace, containerID, netns, deviceID, ifName, nicType string) error {
这个参数在 windows 系统没有用到不需要修改

2024-09-18 02:09 UTC, liyh-yusur commented on pkg/daemon/ovs_windows.go
> +func (csh cniServerHandler) deleteNic(podName, podNamespace, containerID, netns, deviceID, ifName, nicType string) error {
此处已恢复到更改前代码

2024-09-18 02:34 UTC, liyh-yusur commented on pkg/daemon/ovs_windows.go
> +func (csh cniServerHandler) deleteNic(podName, podNamespace, containerID, netns, deviceID, ifName, nicType string) error {
"not enough arguments in call to csh.deleteNic", 前面的函数调用需要，这里得去掉最后一个参数了

2024-09-19 13:16 UTC, merged