add namespaceLabelSelector field in subnet
kubeovn/kube-ovn pull request #4520
Opened 2024-09-13 08:05 UTC by hongzhen-ma

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR
- Features

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-10-10 02:02 UTC, zhangzujian commented on pkg/controller/namespace.go
> +		for _, nsSelector := range s.Spec.NamespaceSelector {
如果 namespace 在 .spec.namespaces 里也在 namespace selector 里，是不是就重复了？

2024-10-10 02:04 UTC, zhangzujian commented on pkg/controller/namespace.go
> +			c.addNamespaceQueue.Add(newNs.Name)
slices.Equal 作比较的时候也会看 element 顺序，这里是不是用 set 比较好。

2024-10-10 02:39 UTC, hongzhen-ma commented on pkg/controller/namespace.go
> +		for _, nsSelector := range s.Spec.NamespaceSelector {
这个场景测试过了。这种重复情况，在下边的 break 逻辑中返回了，不重复添加，避免了这个问题。

2024-10-10 02:39 UTC, hongzhen-ma commented on pkg/controller/namespace.go
> +			c.addNamespaceQueue.Add(newNs.Name)
我改一下

2024-10-10 06:32 UTC, oilbeater requested changes

2024-10-10 06:32 UTC, oilbeater commented on pkg/apis/kubeovn/v1/types.go
> +	NamespaceSelector      []metav1.LabelSelector        `json:"namespaceSelector"`
status 不需要重复字段

2024-10-10 07:20 UTC, hongzhen-ma commented on pkg/apis/kubeovn/v1/types.go
> +	NamespaceSelector      []metav1.LabelSelector        `json:"namespaceSelector"`
就是如果 subnet.spec.NamespaceSelector 中删掉了某个 key:value  的组合，匹配这个条件的 ns 就需要更新，把匹配的子网去掉。
但是subnet 进入更新流程的时候，只有最新的subnet.spec 信息，删掉了那些匹配条件是不清楚的，也就无法触发 ns 更新。所以总是要有个地方，来记录删除了哪些 selector 匹配条件。
要么就只能在subnet update入队的时候，就做匹配检查，把删掉的匹配条件对应的ns 过滤出来。这个动作放在入队处理中，不太合适。

所以之前考虑最后是在 status 中保存一份删除前的匹配条件，跟更新后的 spec 中的条件对比，可以确认增加或删除了哪些匹配条件，从而过滤出对应的ns 去更新

2024-10-10 07:41 UTC, oilbeater commented on pkg/apis/kubeovn/v1/types.go
> +	NamespaceSelector      []metav1.LabelSelector        `json:"namespaceSelector"`
直接检查所有 ns 是不是符合就可以不需要过滤

2024-10-11 10:38 UTC, oilbeater approved these changes

2024-10-11 14:51 UTC, merged