add ut for ovn-nb-suite_test
kubeovn/kube-ovn pull request #4651
Opened 2024-10-23 08:28 UTC by lynn901

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Tests

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-10-23 08:50 UTC, bobz965 requested changes

2024-10-23 08:50 UTC, bobz965 commented on pkg/ovs/ovn-nb-logical_router_port_test.go
> +	t.Run("add new logical router port without wronglr", func(t *testing.T) {
t.Run("add new logical router port  wrong lr",    ?

2024-10-23 08:50 UTC, bobz965 commented on pkg/ovs/ovn-nb-suite_test.go
>  	suite.testlogicalRouterPortFilter()
这个地方的驼峰有问题，也帮忙修改下

2024-10-24 09:54 UTC, lynn901 commented on pkg/ovs/ovn-nb-logical_router_port_test.go
> +	t.Run("add new logical router port without wronglr", func(t *testing.T) {
resolved

2024-10-24 09:58 UTC, bobz965 approved these changes

2024-10-25 05:56 UTC, merged