add process for lb-svc ports update
kubeovn/kube-ovn pull request #4660
Opened 2024-10-24 15:06 UTC by hongzhen-ma

# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR
- Bug fixes

## Which issue(s) this PR fixes

Fixes #4640

2024-10-28 06:01 UTC, oilbeater requested changes

2024-10-28 06:01 UTC, oilbeater commented on pkg/controller/service.go
> +			klog.Infof("flush dnat rules for lb svc %s in pod %s", key, pod.Name)
flush 可能会导致连接中断，需要考虑降低更新对已有流量的影响

2024-10-30 03:13 UTC, hongzhen-ma commented on pkg/controller/service.go
> +			klog.Infof("flush dnat rules for lb svc %s in pod %s", key, pod.Name)
已修改

2024-11-05 06:20 UTC, oilbeater approved these changes

2024-11-05 06:31 UTC, merged