vpc-nat-gateway: ECMP HA mode
kubeovn/kube-ovn pull request #4692
Opened 2024-11-04 10:27 UTC by zhangzujian

# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-11-21 20:18 UTC, patriziobassi commented
would there be the possibility to have more than one egress gw? for instance we may want to select different egress gw IPs for different workload in order to filter on a firewall/router

2024-11-28 02:35 UTC, oilbeater requested changes

2024-11-28 02:35 UTC, oilbeater commented on pkg/controller/controller.go
> +	deploymentInformer := informerFactory.Apps().V1().Deployments()
最好能过滤一下，避免不必要的内存开销

2024-11-28 02:35 UTC, oilbeater commented on pkg/util/pod_routes.go
> +type PodRoutes map[string]map[string][]string
定义一个新的结构？这个嵌套定义看起来太复杂了

2024-11-29 02:20 UTC, zhangzujian commented on pkg/controller/controller.go
> +	deploymentInformer := informerFactory.Apps().V1().Deployments()
done

2024-11-29 02:20 UTC, zhangzujian commented on pkg/util/pod_routes.go
> +type PodRoutes map[string]map[string][]string
已修改

2024-12-03 01:47 UTC, oilbeater approved these changes

2024-12-03 01:48 UTC, merged

2024-12-09 07:46 UTC, zsxsoft commented
any doc?

2024-12-09 08:34 UTC, zhangzujian commented
> any doc?

Document will be added later soon.

2024-12-12 03:29 UTC, zhangzujian commented
@patriziobassi @zsxsoft  Here is the [document](https://kubeovn.github.io/docs/v1.14.x/en/advance/vpc-egress-gateway/).