vpc: add support for dedicated BFD LRP
kubeovn/kube-ovn pull request #4717
Opened 2024-11-08 06:33 UTC by zhangzujian

# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests

## Which issue(s) this PR fixes

Fixes #(issue-number)

2024-11-18 07:55 UTC, oilbeater requested changes

2024-11-18 07:55 UTC, oilbeater commented on pkg/ovs/ovn-nb-logical_router_port.go
> +	lrp.Networks = slices.Clone(networks)
这里为啥要 clone

2024-11-18 07:55 UTC, oilbeater commented on pkg/ovs/ovn-nb-ha_chassis_group.go
> +func (c *OVNNbClient) DeleteHAChassisGroup(name string) error {
删除需不需要加超时

2024-11-19 07:36 UTC, zhangzujian commented on pkg/ovs/ovn-nb-ha_chassis_group.go
> +func (c *OVNNbClient) DeleteHAChassisGroup(name string) error {
调用的函数都已经带超时了，这里不需要加。

2024-11-20 01:44 UTC, oilbeater approved these changes

2024-11-20 01:51 UTC, merged