Add single node e2e test scenario
kubeovn/kube-ovn pull request #740
Opened 2021-04-12 11:14 UTC by lut777

2021-04-12 11:44 UTC, oilbeater commented
Please squash to one commit

2021-04-12 11:47 UTC, oilbeater requested changes

2021-04-12 11:47 UTC, oilbeater commented on actionTrigger.md
> +test
no need here

2021-04-12 12:34 UTC, lut777 commented
done.

2021-04-12 14:10 UTC, lut777 commented
done

2021-04-12 14:11 UTC, lut777 commented on actionTrigger.md
> +test
file removed.

2021-04-13 00:57 UTC, oilbeater approved these changes

2021-04-13 00:57 UTC, merged