feat: feat: vpc load balancer
kubeovn/kube-ovn pull request #883
Opened 2021-06-18 04:26 UTC by fanriming

#### What type of this PR
Examples of user facing changes:
- API changes

With the annotation "ovn.kubernetes.io/ vpc",  the service ClusterIP can be accessed in VPC.

2021-06-18 06:35 UTC, oilbeater requested changes

2021-06-18 06:35 UTC, oilbeater commented on pkg/ovs/ovn-nbctl.go
> +			continue
should log error here

2021-06-19 06:27 UTC, fanriming commented on pkg/ovs/ovn-nbctl.go
> +			continue
Add the warning log here

2021-06-21 02:14 UTC, oilbeater approved these changes

2021-06-21 02:42 UTC, merged