fix openstackonkubernetes doc bugs
kubeovn/kube-ovn pull request #942
Opened 2021-07-23 02:46 UTC by lut777

fix the order in which ns/subnet/vpc is created/modified.

2021-07-23 07:55 UTC, oilbeater requested changes

2021-07-23 07:55 UTC, oilbeater commented on docs/OpenstackOnKubernetes.md
> +2. Add the subnet to the VPC.
subnet->namespace

2021-07-23 08:48 UTC, lut777 commented on docs/OpenstackOnKubernetes.md
> +2. Add the subnet to the VPC.
fixed

2021-07-25 02:52 UTC, oilbeater approved these changes

2021-07-27 07:47 UTC, merged